# ===============================================================
# DevOpsSimulator Configuration File
# Version: 1.0.0 (Stable Production)
# ---------------------------------------------------------------
# NOTE:
# - This configuration prioritizes stability and backward compatibility.
# - Experimental features are commented out and should only be enabled
#   for testing or staging environments — not for production.
# ===============================================================

application:
  name: DevOpsSimulator
  version: 1.0.0
  environment: production
  # experimental_mode: false   # Uncomment to enable experimental features

server:
  host: 0.0.0.0
  port: 8080
  ssl_enabled: true
  # multi_port: [9000, 9001, 9002]   # Experimental: Multi-port server support

logging:
  level: INFO
  format: json
  # format: structured               # Experimental structured logging
  # output: /var/log/experimental.log
  # ai_analysis: disabled            # Experimental AI-based log analysis

# ---------------------------------------------------------------
# Development configuration (enabled via environment variable)
# ---------------------------------------------------------------
development:
  enabled: false
  port: 3000
  hot_reload: false
  debug_mode: false
  mock_apis: false

# ---------------------------------------------------------------
# Experimental Features (Not Production-Ready)
# ---------------------------------------------------------------
# The following configuration represents DevOpsSimulator v3.0.0-experimental.
# Enable only if you understand the risks. These features are behind flags
# for controlled rollout or testing environments.
# ---------------------------------------------------------------

# application:
#   version: 3.0.0-experimental
#   environment: testing
#   experimental_mode: true

# server:
#   port: 9000
#   ssl_enabled: true
#   multi_port: [9000, 9001, 9002]

# logging:
#   level: TRACE
#   format: structured
#   output: /var/log/experimental.log
#   ai_analysis: enabled

# database:
#   host: cluster.example.com
#   port: 5432
#   name: devops_experimental
#   distributed: true

# features:
#   auto_scaling: advanced
#   load_balancer: ai-optimized
#   backup_enabled: true
#   chaos_engineering: enabled

# ai_features:
#   predictive_scaling: true
#   anomaly_detection: true
#   auto_optimization: true
#   model_version: "v2.1.0"

# cloud_providers:
#   - aws
#   - azure
#   - gcp
#   - digitalocean

# security:
#   zero_trust: enabled
#   encryption: AES-256
#   audit_logging: comprehensive
